Bring in results with alaska and target. Bring in census pull with alaska. See if you can join them.

In [1]:
import pandas as pd
from pickle import load
from pickle import dump
import numpy as np
pd.set_option("max_rows", None)
pd.set_option("max_columns", None)

In [2]:
results = load(open('../PICKLES/combined_results.pkl', 'rb'))

In [3]:
race = load(open('../PICKLES/df_race1.pkl', 'rb'))

In [4]:
poverty = load(open('../PICKLES/poverty.pkl', 'rb'))

In [5]:
results.head()

,State,County,2016_total_votes,Obama,Romney,2012_total_votes,2010_land_area,Density,central_outlying,Target
0,Alabama,Autauga,24661.0,6354.0,17366.0,23909.0,594,93.0,Central,Trump
1,Alabama,Baldwin,94090.0,18329.0,65772.0,84988.0,1590,128.0,Central,Trump
2,Alabama,Barbour,10390.0,5873.0,5539.0,11459.0,885,30.0,Central,Trump
3,Alabama,Bibb,8748.0,2200.0,6131.0,8391.0,623,36.0,Outlying,Trump
4,Alabama,Blount,25384.0,2961.0,20741.0,23980.0,645,89.0,Outlying,Trump

In [6]:
race.head()

1,id,total_pop,total_pop_one_race,pop_white,pop_african_american,pop_native,pop_asian,pop_islander,pop_other,total_pop_two_races,County,State
0,0500000US01001,58805.0,55648.0,42160.0,11445.0,217.0,881.0,35.0,910.0,3157.0,Autauga,Alabama
1,0500000US01003,231767.0,216743.0,189399.0,18217.0,1582.0,2067.0,143.0,5335.0,15024.0,Baldwin,Alabama
2,0500000US01005,25223.0,24523.0,11317.0,11933.0,116.0,117.0,1.0,1039.0,700.0,Barbour,Alabama
3,0500000US01007,22293.0,21534.0,16555.0,4413.0,60.0,32.0,9.0,465.0,759.0,Bibb,Alabama
4,0500000US01009,59134.0,55478.0,50663.0,845.0,337.0,178.0,24.0,3431.0,3656.0,Blount,Alabama

In [7]:
results.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3141 entries, 0 to 3140
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   State             3141 non-null   object
 1   County            3141 non-null   object
 2   2016_total_votes  3141 non-null   float64
 3   Obama             3141 non-null   float64
 4   Romney            3141 non-null   float64
 5   2012_total_votes  3141 non-null   float64
 6   2010_land_area    3141 non-null   int64
 7   Density           3141 non-null   float64
 8   central_outlying  3141 non-null   object
 9   Target            3141 non-null   object
dtypes: float64(5), int64(1), object(4)
memory usage: 245.5+ KB

In [8]:
race.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3141 entries, 0 to 3140
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    3141 non-null   object
 1   total_pop             3141 non-null   float64
 2   total_pop_one_race    3141 non-null   float64
 3   pop_white             3141 non-null   float64
 4   pop_african_american  3141 non-null   float64
 5   pop_native            3141 non-null   float64
 6   pop_asian             3141 non-null   float64
 7   pop_islander          3141 non-null   float64
 8   pop_other             3141 non-null   float64
 9   total_pop_two_races   3141 non-null   float64
 10  County                3141 non-null   object
 11  State                 3141 non-null   object
dtypes: float64(9), object(3)
memory usage: 294.6+ KB

In [9]:
df = race.reset_index(drop=True).merge(results.reset_index(drop=True), left_index=True, right_index=True)

In [10]:
df = df.replace('rural', 'Rural')

In [11]:
df.tail()

,id,total_pop,total_pop_one_race,pop_white,pop_african_american,pop_native,pop_asian,pop_islander,pop_other,total_pop_two_races,County_x,State_x,State_y,County_y,2016_total_votes,Obama,Romney,2012_total_votes,2010_land_area,Density,central_outlying,Target
3136,0500000US56037,42272.0,38061.0,34389.0,366.0,433.0,295.0,70.0,2508.0,4211.0,Sweetwater,Wyoming,Wyoming,Sweetwater,16661.0,4773.0,11427.0,16750.0,10427,4.0,Central,Trump
3137,0500000US56039,23331.0,21179.0,19202.0,55.0,185.0,317.0,5.0,1415.0,2152.0,Teton,Wyoming,Wyoming,Teton,12176.0,6211.0,4858.0,11356.0,3995,6.0,Central,Clinton
3138,0500000US56041,20450.0,19269.0,18007.0,66.0,191.0,114.0,27.0,864.0,1181.0,Uinta,Wyoming,Wyoming,Uinta,8053.0,1628.0,6613.0,8453.0,2081,10.0,Central,Trump
3139,0500000US56043,7685.0,7113.0,6600.0,12.0,77.0,33.0,3.0,388.0,572.0,Washakie,Wyoming,Wyoming,Washakie,3715.0,794.0,3013.0,3911.0,2239,4.0,Rural,Trump
3140,0500000US56045,6838.0,6498.0,6197.0,30.0,97.0,27.0,9.0,138.0,340.0,Weston,Wyoming,Wyoming,Weston,3334.0,422.0,2821.0,3323.0,2398,3.0,Rural,Trump

In [12]:
race_poverty_results = df.reset_index(drop=True).merge(poverty.reset_index(drop=True), left_index=True, right_index=True)

In [16]:
race_poverty_results.loc[race_poverty_results.state == 'Alaska']

,id,total_pop,total_pop_one_race,pop_white,pop_african_american,pop_native,pop_asian,pop_islander,pop_other,total_pop_two_races,County_x,State_x,State_y,County_y,2016_total_votes,Obama,Romney,2012_total_votes,2010_land_area,Density,central_outlying,Target,state,county,poverty_total,poverty_under_18,median_household_income
67,0500000US02013,3420.0,3212.0,684.0,297.0,802.0,771.0,32.0,626.0,208.0,Aleutians East,Alaska,Alaska,Aleutians East,529.293851,234.120530,292.395684,549.375577,6982,0.49,Rural,Trump,Alaska,Aleutians East,527.0,61.0,47077.0
68,0500000US02016,5232.0,4858.0,1667.0,259.0,728.0,1513.0,239.0,452.0,374.0,Aleutians West,Alaska,Alaska,Aleutians West,1213.502975,777.428504,426.573343,1238.761919,4390,1.19,Rural,Clinton,Alaska,Aleutians West,482.0,86.0,58517.0
69,0500000US02020,291247.0,250445.0,164446.0,14576.0,23661.0,27646.0,10001.0,10115.0,40802.0,Anchorage,Alaska,Alaska,Anchorage,130040.329900,54042.760210,66387.084670,125169.133300,1705,170.62,Central,Trump,Alaska,Anchorage,27351.0,9009.0,70524.0
70,0500000US02050,18666.0,17650.0,1665.0,85.0,15632.0,202.0,2.0,64.0,1016.0,Bethel,Alaska,Alaska,Bethel,4892.232820,3425.621480,1151.530057,4810.611592,40570,0.46,Rural,Clinton,Alaska,Bethel,3794.0,1842.0,45481.0
71,0500000US02060,844.0,701.0,370.0,6.0,305.0,5.0,3.0,12.0,143.0,Bristol Bay,Alaska,Alaska,Bristol Bay,453.270615,147.147402,251.541638,425.845526,504,1.75,Rural,Trump,Alaska,Bristol Bay,86.0,21.0,62912.0
72,0500000US02068,1619.0,1480.0,1382.0,11.0,61.0,13.0,5.0,8.0,139.0,Denali,Alaska,Alaska,Denali,1105.604027,406.718092,473.883607,922.785544,12751,0.13,Rural,Trump,Alaska,Denali,102.0,28.0,61004.0
73,0500000US02070,4857.0,4361.0,799.0,25.0,3453.0,48.0,9.0,27.0,496.0,Dillingham,Alaska,Alaska,Dillingham,1883.368093,967.896564,590.972108,1639.278557,18569,0.26,Rural,Clinton,Alaska,Dillingham,995.0,458.0,46845.0
74,0500000US02090,95655.0,83485.0,65971.0,4014.0,7555.0,3104.0,604.0,2237.0,12170.0,Fairbanks North Star,Alaska,Alaska,Fairbanks North Star,40876.375840,14710.459690,23755.548490,40539.238280,7338,13.04,Central,Trump,Alaska,Fairbanks North Star,8804.0,3087.0,60472.0
75,0500000US02100,2080.0,1838.0,1589.0,2.0,214.0,14.0,2.0,17.0,242.0,Haines,Alaska,Alaska,Haines,1637.431772,594.965906,625.541085,1310.479513,2319,0.89,Rural,Clinton,Alaska,Haines,304.0,97.0,46111.0
76,0500000US02105,2365.0,2081.0,1147.0,6.0,878.0,16.0,5.0,29.0,284.0,HoonahAngoon,Alaska,Alaska,Hoonah-Angoon,1411.844740,743.645936,453.576123,1255.174007,7525,0.36,Rural,Clinton,Alaska,HoonahAngoon,416.0,107.0,38122.0
77,0500000US02110,32255.0,27318.0,20124.0,350.0,3614.0,2101.0,476.0,653.0,4937.0,Juneau,Alaska,Alaska,Juneau,16436.908530,9253.246898,6110.863835,16116.435260,2702,11.93,Rural,Clinton,Alaska,Juneau,2524.0,723.0,69844.0
78,0500000US02122,58799.0,52811.0,46382.0,386.0,4228.0,809.0,182.0,824.0,5988.0,Kenai Peninsula,Alaska,Alaska,Kenai Peninsula,28840.627170,7726.077223,17148.857390,25995.417540,16075,3.67,Rural,Trump,Alaska,Kenai Peninsula,5798.0,1847.0,57347.0
79,0500000US02130,13948.0,12246.0,8430.0,103.0,2334.0,1129.0,26.0,224.0,1702.0,Ketchikan Gateway,Alaska,Alaska,Ketchikan Gateway,6267.150170,2262.784210,3266.635409,5905.592707,4858,2.87,Rural,Trump,Alaska,Ketchikan Gateway,1335.0,459.0,58073.0
80,0500000US02150,13101.0,11794.0,6570.0,90.0,1826.0,2803.0,117.0,388.0,1307.0,Kodiak Isl,Alaska,Alaska,Kodiak Isl,5764.475667,2080.503695,3061.934499,5369.370069,6550,1.96,Rural,Trump,Alaska,Kodiak Island,1116.0,382.0,59847.0
81,0500000US02158,8368.0,8176.0,173.0,16.0,7946.0,23.0,0.0,18.0,192.0,Kusilvak,Alaska,Alaska,Kusilvak,2018.481387,1715.490873,389.383571,2228.141959,17081,0.49,Rural,Clinton,Alaska,Kusilvak,307.0,102.0,42752.0
82,0500000US02164,1476.0,1309.0,303.0,2.0,994.0,9.0,1.0,0.0,167.0,Lake Peninsula,Alaska,Alaska,Lake Peninsula,496.302635,211.510511,143.052746,371.903785,23652,0.06,Rural,Clinton,Alaska,Lake and Peninsula,287.0,117.0,39794.0
83,0500000US02170,107081.0,94782.0,83035.0,1121.0,6844.0,1559.0,506.0,1717.0,12299.0,MatanuskaSusitna,Alaska,Alaska,Matanuska-Susitna,44911.876200,9327.004548,27325.918520,38343.156530,24608,4.33,Outlying,Trump,Alaska,MatanuskaSusitna,9618.0,3565.0,68670.0
84,0500000US02180,10046.0,9205.0,1422.0,55.0,7556.0,111.0,5.0,56.0,841.0,Nome,Alaska,Alaska,Nome,3242.820912,2264.899663,1095.360112,3558.533046,22962,0.44,Rural,Clinton,Alaska,Nome,2295.0,989.0,43147.0
85,0500000US02185,11031.0,10072.0,3082.0,162.0,5748.0,641.0,321.0,118.0,959.0,North Slope,Alaska,Alaska,North Slope,2302.501355,1406.874910,735.408875,2232.977899,88695,0.12,Rural,Clinton,Alaska,North Slope,1074.0,294.0,68744.0
86,0500000US02188,7793.0,7331.0,700.0,72.0,6469.0,55.0,12.0,23.0,462.0,Northwest Arctic,Alaska,Alaska,Northwest Arctic,2148.834688,1310.125090,611.591125,2002.022101,35573,0.22,Rural,Clinton,Alaska,Northwest Arctic,1494.0,572.0,49466.0
87,0500000US02195,3398.0,2962.0,2470.0,49.0,247.0,123.0,12.0,61.0,436.0,Petersburg,Alaska,Alaska,Petersburg,1706.007455,776.066018,867.459549,1729.880554,3282,1.17,Rural,Trump,Alaska,Petersburg,406.0,135.0,52294.0
88,0500000US02198,5753.0,5095.0,2403.0,22.0,2584.0,27.0,30.0,29.0,658.0,Prince of WalesHyder,Alaska,Alaska,Prince of Wales-Hyder,2830.673904,1298.248629,1045.101630,2482.062762,3923,1.09,Rural,Trump,Alaska,Prince of WalesHyder,957.0,334.0,40756.0
89,0500000US02220,8458.0,7261.0,5174.0,37.0,1248.0,573.0,14.0,215.0,1197.0,Sitka,Alaska,Alaska,Sitka,4427.915868,2340.002643,1830.694119,4415.265365,2870,2.95,Rural,Clinton,Alaska,Sitka,800.0,244.0,58000.0
90,0500000US02230,1240.0,1160.0,1070.0,10.0,32.0,39.0,0.0,9.0,80.0,Skagway,Alaska,Alaska,Skagway,828.915064,355.408581,187.441963,613.045389,452,2.86,Rural,Clinton,Alaska,Skagway,40.0,11.0,58550.0
91,0500000US02240,6808.0,6216.0,5085.0,74.0,817.0,87.0,16.0,137.0,592.0,Southeast Fairbanks,Alaska,Alaska,Southeast Fairbanks,3406.365158,680.462922,2250.312749,3089.243210,24769,0.27,Rural,Trump,Alaska,Southeast Fairbanks,938.0,393.0,54508.0
92,akcombined,9719.0,8677.0,6518.0,57.0,1332.0,546.0,72.0,152.0,1042.0,Valdez Cordova,Alaska,Alaska,Valdez-Cordova,4449.253456,1575.330231,2523.305413,4343.914388,34240,0.28,Rural,Trump,Alaska,ValdezCordova,858.0,262.0,60297.0
93,0500000US02275,2127.0,1789.0,1352.0,0.0,380.0,25.0,2.0,30.0,338.0,Wrangell,Alaska,Alaska,Wrangell,1124.152497,362.631179,738.686288,1143.064441,2541,0.83,Rural,Trump,Alaska,Wade Hampton,2530.0,1403.0,30883.0
94,0500000US02282,662.0,544.0,249.0,4.0,255.0,32.0,1.0,3.0,118.0,Yakutat,Alaska,Alaska,Yakutat,343.085908,171.117423,122.283038,305.291588,7649,0.09,Rural,Clinton,Alaska,Yakutat,97.0,40.0,49331.0
95,0500000US02290,5343.0,5008.0,1130.0,7.0,3832.0,8.0,3.0,28.0,335.0,YukonKoyukuk,Alaska,Alaska,Yukon-Koyukuk,2676.397380,1471.450436,813.062373,2388.997632,145505,0.04,Rural,Clinton,Alaska,YukonKoyukuk,1512.0,541.0,35177.0

In [14]:
dump(race_poverty_results, open('race_poverty_results.pkl', 'wb'))

In [15]:
dump(df, open('results_race_with_alaska.pkl', 'wb'))