In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('2016 Presidential Election Analysis.csv')

In [3]:
df.head()

,State Code,County Name,County Population,Clinton or Trump State,Clinton,Trump,Total,% Clinton,% Trump,Vote Difference C-T,...,County FIPS Code,CBSA Code,CSA Code,CBSA Title,CBSA Population,Metropolitan/Micropolitan Statistical Area,CSA Title,Metropolitan Division Title,Metropolitan Division Code,Central/Outlying County
0,AL,Autauga County,"55,347",Trump,"5,908","18,110","24,661",23.96%,73.44%,"(12,202)",...,1.0,33860.0,NaN,"Montgomery, AL","373,792",Metropolitan Statistical Area,NaN,NaN,NaN,Central
1,AL,Baldwin County,"203,709",Trump,"18,409","72,780","94,090",19.57%,77.35%,"(54,371)",...,3.0,19300.0,380.0,"Daphne-Fairhope-Foley, AL","203,709",Metropolitan Statistical Area,"Mobile-Daphne-Fairhope, AL",NaN,NaN,Central
2,AL,Barbour County,"26,489",Trump,"4,848","5,431","10,390",46.66%,52.27%,(583),...,5.0,21640.0,NaN,"Eufaula, AL-GA",NaN,Micropolitan Statistical Area,NaN,NaN,NaN,Central
3,AL,Bibb County,"22,583",Trump,"1,874","6,733","8,748",21.42%,76.97%,"(4,859)",...,7.0,13820.0,142.0,"Birmingham-Hoover, AL","1,145,647",Metropolitan Statistical Area,"Birmingham-Hoover-Talladega, AL",NaN,NaN,Outlying
4,AL,Blount County,"57,673",Trump,"2,150","22,808","25,384",8.47%,89.85%,"(20,658)",...,9.0,13820.0,142.0,"Birmingham-Hoover, AL","1,145,647",Metropolitan Statistical Area,"Birmingham-Hoover-Talladega, AL",NaN,NaN,Outlying

In [4]:
df.loc[df['County FIPS Code'] == 39.0]

,State Code,County Name,County Population,Clinton or Trump State,Clinton,Trump,Total,% Clinton,% Trump,Vote Difference C-T,...,County FIPS Code,CBSA Code,CSA Code,CBSA Title,CBSA Population,Metropolitan/Micropolitan Statistical Area,CSA Title,Metropolitan Division Title,Metropolitan Division Code,Central/Outlying County
19,AL,Covington County,"37,835",Trump,"2,379","13,222","15,818",15.04%,83.59%,"(10,843)",...,39.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Not Metro or Micro, Presumed Rural"
102,AR,Dallas County,"7,604",Trump,"1,165","1,507","2,741",42.50%,54.98%,(342),...,39.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Not Metro or Micro, Presumed Rural"
177,CA,Madera County,"154,998",Clinton,"13,283","19,221","34,263",38.77%,56.10%,"(5,938)",...,39.0,31460.0,260.0,"Madera, CA","154,998",Metropolitan Statistical Area,"Fresno-Madera, CA",NaN,NaN,Central
236,CO,Elbert County,"24,735",Clinton,"3,056","11,536","15,689",19.48%,73.53%,"(8,480)",...,39.0,19740.0,216.0,"Denver-Aurora-Lakewood, CO","2,814,330",Metropolitan Statistical Area,"Denver-Aurora, CO",NaN,NaN,Outlying
310,FL,Gadsden County,"46,036",Trump,"14,994","6,721","22,079",67.91%,30.44%,"8,273",...,39.0,45220.0,533.0,"Tallahassee, FL","377,924",Metropolitan Statistical Area,"Tallahassee-Bainbridge, FL-GA",NaN,NaN,Outlying
378,GA,Camden County,"52,102",Trump,"5,914","12,287","18,825",31.42%,65.27%,"(6,373)",...,39.0,41220.0,300.0,"St. Marys, GA",NaN,Micropolitan Statistical Area,"Jacksonville-St. Marys-Palatka, FL-GA",NaN,NaN,Central
541,ID,Elmore County,"25,876",Trump,"1,814","5,816","8,519",21.29%,68.27%,"(4,002)",...,39.0,34300.0,147.0,"Mountain Home, ID",NaN,Micropolitan Statistical Area,"Boise City-Mountain Home-Ontario, ID-OR",NaN,NaN,Central
585,IL,De Witt County,"16,247",Clinton,"1,907","5,072","7,469",25.53%,67.91%,"(3,165)",...,39.0,14010.0,145.0,"Bloomington, IL","189,413",Metropolitan Statistical Area,"Bloomington-Pontiac, IL",NaN,NaN,Outlying
687,IN,Elkhart County,"203,474",Trump,"20,667","41,810","65,187",31.70%,64.14%,"(21,143)",...,39.0,21140.0,515.0,"Elkhart-Goshen, IN","203,474",Metropolitan Statistical Area,"South Bend-Elkhart-Mishawaka, IN-MI",NaN,NaN,Central
779,IA,Clarke County,"9,259",Trump,"1,463","2,706","4,405",33.21%,61.43%,"(1,243)",...,39.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Not Metro or Micro, Presumed Rural"
878,KS,Decatur County,"2,932",Trump,178,"1,220","1,460",12.19%,83.56%,"(1,042)",...,39.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Not Metro or Micro, Presumed Rural"
983,KY,Carlisle County,"4,874",Trump,432,"2,094","2,599",16.62%,80.57%,"(1,662)",...,39.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Not Metro or Micro, Presumed Rural"
1103,LA,Evangeline Parish,"33,743",Trump,"4,208","10,357","14,879",28.28%,69.61%,"(6,149)",...,39.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Not Metro or Micro, Presumed Rural"
1182,MD,Somerset County,"25,768",Clinton,"3,484","5,056","8,768",39.74%,57.66%,"(1,572)",...,39.0,41540.0,NaN,"Salisbury, MD-DE","395,300",Metropolitan Statistical Area,NaN,NaN,NaN,Outlying
1221,MI,Crawford County,"13,801",Trump,"2,110","4,354","6,833",30.88%,63.72%,"(2,244)",...,39.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Not Metro or Micro, Presumed Rural"
1304,MN,Dodge County,"20,364",Clinton,"3,102","6,527","10,564",29.36%,61.79%,"(3,425)",...,39.0,40340.0,462.0,"Rochester, MN","213,873",Metropolitan Statistical Area,"Rochester-Austin, MN",NaN,NaN,Outlying
1391,MS,George County,"23,373",Trump,"1,013","8,652","9,831",10.30%,88.01%,"(7,639)",...,39.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Not Metro or Micro, Presumed Rural"
1473,MO,Cedar County,"13,934",Trump,"1,010","5,019","6,278",16.09%,79.95%,"(4,009)",...,39.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Not Metro or Micro, Presumed Rural"
1588,MT,Granite County,"3,240",Trump,469,"1,185","1,762",26.62%,67.25%,(716),...,39.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Not Metro or Micro, Presumed Rural"
1644,NE,Cuming County,"9,125",Trump,712,"3,095","3,988",17.85%,77.61%,"(2,383)",...,39.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Not Metro or Micro, Presumed Rural"
1764,NJ,Union County,"555,786",Clinton,"145,412","67,582","219,385",66.28%,30.81%,"77,830",...,39.0,35620.0,408.0,"New York-Newark-Jersey City, NY-NJ-PA","20,182,305",Metropolitan Statistical Area,"New York-Newark, NY-NJ-CT-PA","Newark, NJ-PA",35084.0,Central
1787,NM,Rio Arriba County,"39,465",Clinton,"9,534","3,583","14,767",64.56%,24.26%,"5,951",...,39.0,21580.0,106.0,"Espaï¿½ola, NM",NaN,Micropolitan Statistical Area,"Albuquerque-Santa Fe-Las Vegas, NM",NaN,NaN,Central
1818,NY,Greene County,"47,625",Clinton,"6,370","11,546","18,869",33.76%,61.19%,"(5,176)",...,39.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Not Metro or Micro, Presumed Rural"
1880,NC,Cherokee County,"27,178",Trump,"2,809","10,711","13,860",20.27%,77.28%,"(7,902)",...,39.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Not Metro or Micro, Presumed Rural"
1980,ND,Griggs County,"2,314",Trump,298,847,"1,247",23.90%,67.92%,(549),...,39.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Not Metro or Micro, Presumed Rural"
2033,OH,Defiance County,"38,352",Trump,"5,282","11,478","17,795",29.68%,64.50%,"(6,196)",...,39.0,19580.0,NaN,"Defiance, OH",NaN,Micropolitan Statistical Area,NaN,NaN,NaN,Central
2121,OK,Custer County,"29,744",Trump,"2,102","7,818","10,531",19.96%,74.24%,"(5,716)",...,39.0,48220.0,NaN,"Weatherford, OK",NaN,Micropolitan Statistical Area,NaN,NaN,NaN,Central
2198,OR,Lane County,"362,895",Clinton,"100,497","66,218","181,072",55.50%,36.57%,"34,279",...,39.0,21660.0,NaN,"Eugene, OR","362,895",Metropolitan Statistical Area,NaN,NaN,NaN,Central
2234,PA,Crawford County,"86,484",Trump,"10,215","23,912","35,563",28.72%,67.24%,"(13,697)",...,39.0,32740.0,240.0,"Meadville, PA",NaN,Micropolitan Statistical Area,"Erie-Meadville, PA",NaN,NaN,Central
2306,SC,Fairfield County,"22,747",Trump,"6,936","4,024","11,252",61.64%,35.76%,"2,912",...,39.0,17900.0,192.0,"Columbia, SC","810,068",Metropolitan Statistical Area,"Columbia-Orangeburg-Newberry, SC",NaN,NaN,Outlying
2351,SD,Deuel County,"4,333",Trump,570,"1,366","2,080",27.40%,65.67%,(796),...,39.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Not Metro or Micro, Presumed Rural"
2418,TN,Decatur County,"11,660",Trump,894,"3,580","4,577",19.53%,78.22%,"(2,686)",...,39.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Not Metro or Micro, Presumed Rural"
2513,TX,Brazoria County,"346,312",Trump,"43,075","72,653","120,296",35.81%,60.40%,"(29,578)",...,39.0,26420.0,288.0,"Houston-The Woodlands-Sugar Land, TX","6,656,947",Metropolitan Statistical Area,"Houston-The Woodlands, TX",NaN,NaN,Central
2767,UT,Sanpete County,"28,778",Trump,"1,026","6,436","9,778",10.49%,65.82%,"(5,410)",...,39.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Not Metro or Micro, Presumed Rural"
2943,WA,Klickitat County,"21,026",Clinton,"3,781","5,390","9,859",38.35%,54.67%,"(1,609)",...,39.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Not Metro or Micro, Presumed Rural"
2982,WV,Kanawha County,"188,332",Trump,"27,985","43,464","74,996",37.32%,57.96%,"(15,479)",...,39.0,16620.0,170.0,"Charleston, WV","220,614",Metropolitan Statistical Area,"Charleston-Huntington-Ashland, WV-OH-KY",NaN,NaN,Central
3037,WI,Fond du Lac County,"101,973",Trump,"17,391","31,044","51,094",34.04%,60.76%,"(13,653)",...,39.0,22540.0,NaN,"Fond du Lac, WI","101,973",Metropolitan Statistical Area,NaN,NaN,NaN,Central
3109,WY,Teton County,"23,125",Trump,"7,313","3,920","12,176",60.06%,32.19%,"3,393",...,39.0,27220.0,NaN,"Jackson, WY-ID",NaN,Micropolitan Statistical Area,NaN,NaN,NaN,Central

In [5]:
us_state_abbrev = {
    'AL': 'Alabama',
    'AK': 'Alaska',
    'AZ': 'Arizona',
    'AR': 'Arkansas',
    'CA': 'California',
    'CO': 'Colorado',
    'CT': 'Connecticut',
    'DE': 'Delaware',
    'FL': 'Florida',
    'GA': 'Georgia',
    'HI': 'Hawaii',
    'ID': 'Idaho',
    'IL': 'Illinois',
    'IN': 'Indiana',
    'IA': 'Iowa',
    'KS': 'Kansas',
    'KY': 'Kentucky',
    'LA': 'Louisiana',
    'ME': 'Maine',
    'MD': 'Maryland',
    'MA': 'Massachusetts',
    'MI': 'Michigan',
    'MN': 'Minnesota',
    'MS': 'Mississippi',
    'MO': 'Missouri',
    'MT': 'Montana',
    'NE': 'Nebraska',
    'NV': 'Nevada',
    'NH': 'New Hampshire',
    'NJ': 'New Jersey',
    'NM': 'New Mexico',
    'NY': 'New York',
    'NC': 'North Carolina',
    'ND': 'North Dakota',
    'OH': 'Ohio',
    'OK': 'Oklahoma',
    'OR': 'Oregon',
    'PA': 'Pennsylvania',
    'RI': 'Rhode Island',
    'SC': 'South Carolina',
    'SD': 'South Dakota',
    'TN': 'Tennessee',
    'TX': 'Texas',
    'UT': 'Utah',
    'VT': 'Vermont',
    'VA': 'Virginia',
    'WA': 'Washington',
    'WV': 'West Virginia',
    'WI': 'Wisconsin',
    'WY': 'Wyoming',
}

In [6]:
df['State Code'] = df['State Code'].map(us_state_abbrev).fillna(df['State Code'])

In [7]:
df['State Code'].value_counts()

Texas             254
Georgia           159
Virginia          133
Kentucky          120
Missouri          115
Kansas            105
Illinois          102
North Carolina    100
Iowa               99
Tennessee          95
Nebraska           93
Indiana            92
Ohio               88
Minnesota          87
Michigan           83
Mississippi        82
Oklahoma           77
Arkansas           75
Wisconsin          72
Pennsylvania       67
Florida            67
Alabama            67
South Dakota       66
Colorado           64
Louisiana          64
New York           62
California         58
Montana            56
West Virginia      55
North Dakota       53
South Carolina     46
Idaho              44
Washington         39
Oregon             36
New Mexico         33
Utah               29
Maryland           24
Wyoming            23
New Jersey         21
Nevada             17
Maine              16
Arizona            15
Massachusetts      14
Vermont            14
New Hampshire      10
Connecticut         8
Rhode Island        5
Hawaii              4
Delaware            3
DC                  1
Alaska              1
Name: State Code, dtype: int64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3113 entries, 0 to 3112
Data columns (total 39 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   State Code                                  3113 non-null   object
 1   County Name                                 3113 non-null   object
 2    County Population                          3112 non-null   object
 3   Clinton or Trump State                      3113 non-null   object
 4    Clinton                                    3113 non-null   object
 5    Trump                                      3113 non-null   object
 6    Total                                      3113 non-null   object
 7   % Clinton                                   3113 non-null   object
 8   % Trump                                     3113 non-null   object
 9    Vote Difference C-T                        3113 non-null   object
 10   Vote Difference T-C                        3113 non-null   object
 11  Percent Difference C-T                      3113 non-null   object
 12  Percent Difference T-C                      3113 non-null   object
 13   Obama                                      3113 non-null   object
 14   Romney                                     3113 non-null   object
 15   2012 Total Votes                           3113 non-null   object
 16  % Obama                                     3113 non-null   object
 17  % Romney                                    3113 non-null   object
 18   Vote Difference O-R                        3113 non-null   object
 19  % Difference O-R                            3113 non-null   object
 20  Clinton B(W) Obama                          3113 non-null   object
 21  Trump B(W) Romney                           3113 non-null   object
 22  Clinton % B(W) Obama                        3113 non-null   object
 23  Trump % B(W) Romney                         3113 non-null   object
 24  2010 Land Area                              3113 non-null   int64
 25  Density                                     3113 non-null   int64
 26  Combined FIPS Code                          3113 non-null   object
 27  ANSI Code                                   3113 non-null   object
 28  State FIPS Code                             3112 non-null   float64
 29  County FIPS Code                            3112 non-null   float64
 30  CBSA Code                                   1819 non-null   float64
 31  CSA Code                                    1167 non-null   float64
 32  CBSA Title                                  1819 non-null   object
 33  CBSA Population                             1157 non-null   object
 34  Metropolitan/Micropolitan Statistical Area  1819 non-null   object
 35  CSA Title                                   1167 non-null   object
 36  Metropolitan Division Title                 113 non-null    object
 37  Metropolitan Division Code                  113 non-null    float64
 38  Central/Outlying County                     3113 non-null   object
dtypes: float64(5), int64(2), object(32)
memory usage: 948.6+ KB

In [9]:
from pickle import load

In [10]:
df_race = load(open('df_race.pkl', 'rb'))

In [11]:
df['State Code'].value_counts().count()

51

In [12]:
df_race['State'].value_counts().count()

52

In [13]:
DC = (df_race.loc[df_race['State'].str.contains('District of Columbia', case=False)]).index

In [14]:
DC

Int64Index([322], dtype='int64')

In [15]:
DC = df_race.drop(DC)

In [16]:
df_race.State.str.contains('District of Columbia').value_counts()

False    3220
True        1
Name: State, dtype: int64

In [17]:
df_race.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3221 entries, 2 to 3222
Data columns (total 12 columns):
 #   Column                                                                       Non-Null Count  Dtype
---  ------                                                                       --------------  -----
 0   id                                                                           3221 non-null   object
 1   Total                                                                        3221 non-null   float64
 2   TotalPopulation of one race                                                  3221 non-null   float64
 3   TotalPopulation of one raceWhite alone                                       3221 non-null   float64
 4   TotalPopulation of one raceBlack or African American alone                   3221 non-null   float64
 5   TotalPopulation of one raceAmerican Indian and Alaska Native alone           3221 non-null   float64
 6   TotalPopulation of one raceAsian alone                                       3221 non-null   float64
 7   TotalPopulation of one raceNative Hawaiian and Other Pacific Islander alone  3221 non-null   float64
 8   TotalPopulation of one raceSome Other Race alone                             3221 non-null   float64
 9   TotalPopulation of two or more races                                         3221 non-null   float64
 10  County                                                                       3221 non-null   object
 11  State                                                                        3221 non-null   object
dtypes: float64(9), object(3)
memory usage: 456.2+ KB

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3113 entries, 0 to 3112
Data columns (total 39 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   State Code                                  3113 non-null   object
 1   County Name                                 3113 non-null   object
 2    County Population                          3112 non-null   object
 3   Clinton or Trump State                      3113 non-null   object
 4    Clinton                                    3113 non-null   object
 5    Trump                                      3113 non-null   object
 6    Total                                      3113 non-null   object
 7   % Clinton                                   3113 non-null   object
 8   % Trump                                     3113 non-null   object
 9    Vote Difference C-T                        3113 non-null   object
 10   Vote Difference T-C                        3113 non-null   object
 11  Percent Difference C-T                      3113 non-null   object
 12  Percent Difference T-C                      3113 non-null   object
 13   Obama                                      3113 non-null   object
 14   Romney                                     3113 non-null   object
 15   2012 Total Votes                           3113 non-null   object
 16  % Obama                                     3113 non-null   object
 17  % Romney                                    3113 non-null   object
 18   Vote Difference O-R                        3113 non-null   object
 19  % Difference O-R                            3113 non-null   object
 20  Clinton B(W) Obama                          3113 non-null   object
 21  Trump B(W) Romney                           3113 non-null   object
 22  Clinton % B(W) Obama                        3113 non-null   object
 23  Trump % B(W) Romney                         3113 non-null   object
 24  2010 Land Area                              3113 non-null   int64
 25  Density                                     3113 non-null   int64
 26  Combined FIPS Code                          3113 non-null   object
 27  ANSI Code                                   3113 non-null   object
 28  State FIPS Code                             3112 non-null   float64
 29  County FIPS Code                            3112 non-null   float64
 30  CBSA Code                                   1819 non-null   float64
 31  CSA Code                                    1167 non-null   float64
 32  CBSA Title                                  1819 non-null   object
 33  CBSA Population                             1157 non-null   object
 34  Metropolitan/Micropolitan Statistical Area  1819 non-null   object
 35  CSA Title                                   1167 non-null   object
 36  Metropolitan Division Title                 113 non-null    object
 37  Metropolitan Division Code                  113 non-null    float64
 38  Central/Outlying County                     3113 non-null   object
dtypes: float64(5), int64(2), object(32)
memory usage: 948.6+ KB

In [19]:
# df_race['County'] = df_race['County'].str.rstrip('County')
df['County Name'] = df['County Name'].str.rstrip('County')

In [20]:
df['County Name'].value_counts()

Washington      30
Jefferson       25
Franklin        24
Lincoln         23
Jackson         23
                ..
Crosby           1
Calaveras        1
Goodhue          1
Buena Vista      1
Corson           1
Name: County Name, Length: 1848, dtype: int64

In [21]:
# df_race.where(df['County Name'] is in df_race['County'].values).notna()
df['County Name'].isin(df_race['County']).value_counts()

True     3110
False       3
Name: County Name, dtype: int64

In [22]:
# df_common = df1.loc[df1['set1'].isin(df2['set2'])]

missing = df.loc[~df['County Name'].isin(df_race['County'])]

In [23]:
missing

,State Code,County Name,County Population,Clinton or Trump State,Clinton,Trump,Total,% Clinton,% Trump,Vote Difference C-T,...,County FIPS Code,CBSA Code,CSA Code,CBSA Title,CBSA Population,Metropolitan/Micropolitan Statistical Area,CSA Title,Metropolitan Division Title,Metropolitan Division Code,Central/Outlying County
67,Alaska,Alaska,"738,432",Trump,"93,007","130,415","246,588",37.72%,52.89%,"(37,408)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Z-Alaska
1113,Louisiana,La Salle Parish,"14,974",Trump,605,"5,835","6,568",9.21%,88.84%,"(5,230)",...,59.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Not Metro or Micro, Presumed Rural"
2388,South Dakota,Oglala,NaN,Trump,"2,504",241,"2,896",86.46%,8.32%,"2,263",...,113.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Not Metro or Micro, Presumed Rural"

In [24]:
pd.set_option("max_rows", None)

Why isn't this working??

In [25]:
# (to_replace={'a': None}, value=None, method=None):

In [26]:
df = df.replace('Oglala', 'Oglala Lakota', regex = True)

In [27]:
(df.loc[df['County Name'].str.contains('Oglala', case=False)])

,State Code,County Name,County Population,Clinton or Trump State,Clinton,Trump,Total,% Clinton,% Trump,Vote Difference C-T,...,County FIPS Code,CBSA Code,CSA Code,CBSA Title,CBSA Population,Metropolitan/Micropolitan Statistical Area,CSA Title,Metropolitan Division Title,Metropolitan Division Code,Central/Outlying County
2388,South Dakota,Oglala Lakota,NaN,Trump,"2,504",241,"2,896",86.46%,8.32%,"2,263",...,113.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Not Metro or Micro, Presumed Rural"

In [28]:
df.head()

,State Code,County Name,County Population,Clinton or Trump State,Clinton,Trump,Total,% Clinton,% Trump,Vote Difference C-T,...,County FIPS Code,CBSA Code,CSA Code,CBSA Title,CBSA Population,Metropolitan/Micropolitan Statistical Area,CSA Title,Metropolitan Division Title,Metropolitan Division Code,Central/Outlying County
0,Alabama,Autauga,"55,347",Trump,"5,908","18,110","24,661",23.96%,73.44%,"(12,202)",...,1.0,33860.0,NaN,"Montgomery, AL","373,792",Metropolitan Statistical Area,NaN,NaN,NaN,Central
1,Alabama,Baldwin,"203,709",Trump,"18,409","72,780","94,090",19.57%,77.35%,"(54,371)",...,3.0,19300.0,380.0,"Daphne-Fairhope-Foley, AL","203,709",Metropolitan Statistical Area,"Mobile-Daphne-Fairhope, AL",NaN,NaN,Central
2,Alabama,Barbour,"26,489",Trump,"4,848","5,431","10,390",46.66%,52.27%,(583),...,5.0,21640.0,NaN,"Eufaula, AL-GA",NaN,Micropolitan Statistical Area,NaN,NaN,NaN,Central
3,Alabama,Bibb,"22,583",Trump,"1,874","6,733","8,748",21.42%,76.97%,"(4,859)",...,7.0,13820.0,142.0,"Birmingham-Hoover, AL","1,145,647",Metropolitan Statistical Area,"Birmingham-Hoover-Talladega, AL",NaN,NaN,Outlying
4,Alabama,Blount,"57,673",Trump,"2,150","22,808","25,384",8.47%,89.85%,"(20,658)",...,9.0,13820.0,142.0,"Birmingham-Hoover, AL","1,145,647",Metropolitan Statistical Area,"Birmingham-Hoover-Talladega, AL",NaN,NaN,Outlying

In [31]:
missing = df.loc[~df['County Name'].isin(df_race['County'])]
missing

,State Code,County Name,County Population,Clinton or Trump State,Clinton,Trump,Total,% Clinton,% Trump,Vote Difference C-T,...,County FIPS Code,CBSA Code,CSA Code,CBSA Title,CBSA Population,Metropolitan/Micropolitan Statistical Area,CSA Title,Metropolitan Division Title,Metropolitan Division Code,Central/Outlying County
67,Alaska,Alaska,"738,432",Trump,"93,007","130,415","246,588",37.72%,52.89%,"(37,408)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Z-Alaska
1113,Louisiana,La Salle Parish,"14,974",Trump,605,"5,835","6,568",9.21%,88.84%,"(5,230)",...,59.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Not Metro or Micro, Presumed Rural"

In [32]:
(df.loc[df['State Code'].str.contains('Alaska', case=False)])

,State Code,County Name,County Population,Clinton or Trump State,Clinton,Trump,Total,% Clinton,% Trump,Vote Difference C-T,...,County FIPS Code,CBSA Code,CSA Code,CBSA Title,CBSA Population,Metropolitan/Micropolitan Statistical Area,CSA Title,Metropolitan Division Title,Metropolitan Division Code,Central/Outlying County
67,Alaska,Alaska,"738,432",Trump,"93,007","130,415","246,588",37.72%,52.89%,"(37,408)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Z-Alaska